CREATE DATABASE IF NOT EXISTS mysns
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE mysns;

CREATE TABLE IF NOT EXISTS user (
  id VARCHAR(128) PRIMARY KEY,
  jsonstr VARCHAR(1024)
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS feed (
  no INT UNSIGNED PRIMARY KEY,
  id VARCHAR(128),
  jsonstr VARCHAR(8192),
  comment VARCHAR(1024)
) DEFAULT CHARACTER SET utf8mb4;


CREATE TABLE IF NOT EXISTS friend(
	id VARCHAR(128), -- "email"
	frid VARCHAR(128), -- "email“
	INDEX idx1(id)
);